export enum OutgoingInvoiceStatus {
  DRAFT = "DRAFT",
  READY_TO_SEND = "READY_TO_SEND",
  SENT = "SENT",
  PAYMENT_RECEIVED_PENDING_DELIVERY = "PAYMENT_RECEIVED_PENDING_DELIVERY",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}
