export enum OutgoingInvoiceStatus {
  DRAFT = "DRAFT",
  READY_TO_SEND = "READY_TO_SEND",
  SENT = "SENT",
  PENDING_BANK_TRANSFER = "PENDING_BANK_TRANSFER",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}
