export enum PayInType {
  VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT",
  CREDIT_CARD_FULL_REDIRECT = "CREDIT_CARD_FULL_REDIRECT",
  QRIS = "QRIS",
  CREDIT_CARD_FULL_REDIRECT_INSTALLMENT_3_MONTHS = "CREDIT_CARD_FULL_REDIRECT_INSTALLMENT_3_MONTHS",
  CREDIT_CARD_FULL_REDIRECT_INSTALLMENT_6_MONTHS = "CREDIT_CARD_FULL_REDIRECT_INSTALLMENT_6_MONTHS",
  CREDIT_CARD_FULL_REDIRECT_INSTALLMENT_12_MONTHS = "CREDIT_CARD_FULL_REDIRECT_INSTALLMENT_12_MONTHS",
}
