export const ACCOUNTING_SWR_KEYS = {
  LIST_LEDGER_ACCOUNTS: "list-ledger-accounts",
  LIST_COA_MAPPING_ENTITY_TYPES: "list-coa-mapping-entity-types",
  LIST_COA_MAPPINGS: "list-coa-mappings",
  GET_NERACA_REPORT: "get-neraca-report",
  GET_LABA_RUGI_REPORT: "get-laba-rugi-report",
  GET_ARUS_KAS_REPORT: "get-arus-kas-report",
  GET_TRIAL_BALANCE_REPORT: "get-trial-balance-report",
  GET_GENERAL_LEDGER_REPORT: "get-general-ledger-report",
  GET_CALK_REPORT: "get-calk-report",
  LIST_JOURNALS: "list-journals",
  GET_JOURNAL: "get-journal",
  LIST_TRIAL_BALANCE_LINES: "list-trial-balance-lines",
  GET_OPENING_BALANCE: "get-opening-balance",
  GET_ACCOUNT_SETTING: "get-account-setting",
  LIST_ACCOUNT_SETTING_AUDIT: "list-account-setting-audit",
  LIST_ACCOUNTING_PERIODS: "list-accounting-periods",
  GET_ACCOUNTING_PERIOD: "get-accounting-period",
  GET_ACCOUNTING_YEAR_SUMMARY: "get-accounting-year-summary",
  GET_MANAGERIAL_COST: "get-managerial-cost",
} as const;
