export const ACCOUNTING_SWR_KEYS = {
  LIST_LEDGER_ACCOUNTS: "list-ledger-accounts",
  LIST_COA_MAPPING_ENTITY_TYPES: "list-coa-mapping-entity-types",
  LIST_COA_MAPPINGS: "list-coa-mappings",
  GET_NERACA_REPORT: "get-neraca-report",
  GET_LABA_RUGI_REPORT: "get-laba-rugi-report",
  GET_ARUS_KAS_REPORT: "get-arus-kas-report",
  GET_TRIAL_BALANCE_REPORT: "get-trial-balance-report",
  GET_GENERAL_LEDGER_REPORT: "get-general-ledger-report",
  GET_CALK_REPORT: "get-calk-report",
  LIST_JOURNALS: "list-journals",
  GET_JOURNAL: "get-journal",
  LIST_TRIAL_BALANCE_LINES: "list-trial-balance-lines",
  GET_OPENING_BALANCE: "get-opening-balance",
  GET_ACCOUNT_SETTING: "get-account-setting",
  LIST_ACCOUNT_SETTING_AUDIT: "list-account-setting-audit",
  LIST_ACCOUNTING_PERIODS: "list-accounting-periods",
  GET_ACCOUNTING_PERIOD: "get-accounting-period",
  GET_ACCOUNTING_YEAR_SUMMARY: "get-accounting-year-summary",
  GET_MANAGERIAL_COST: "get-managerial-cost",
  LIST_LEDGER_ENTRIES: "list-ledger-entries",
  GET_ACCOUNT_BALANCE: "get-account-balance",
} as const;

export const ACCOUNTING_MUTATION_KEYS = {
  CREATE_JOURNAL: "create-journal",
  REVERSE_JOURNAL: "reverse-journal",
  CREATE_COA_MAPPING: "create-coa-mapping",
  UPDATE_COA_MAPPING: "update-coa-mapping",
  DELETE_COA_MAPPING: "delete-coa-mapping",
  CREATE_LEDGER_ACCOUNT: "create-ledger-account",
  UPDATE_LEDGER_ACCOUNT: "update-ledger-account",
  DELETE_LEDGER_ACCOUNT: "delete-ledger-account",
  CLOSE_PERIOD: "close-period",
  REOPEN_PERIOD: "reopen-period",
  CLOSE_YEAR: "close-year",
  REOPEN_YEAR: "reopen-year",
  POST_OPENING_BALANCE: "post-opening-balance",
  UPDATE_ACCOUNT_SETTING: "update-account-setting",
  ALLOCATE_MANAGERIAL_COST: "allocate-managerial-cost",
  SETTLE_PPH_FINAL: "settle-pph-final",
} as const;
