export const INVOICE_SWR_KEYS = {
  LIST_INVOICES: "list-invoices",
  GET_INVOICE: "get-invoice",
  GET_INCOMING_INVOICE: "get-incoming-invoice",
  GET_OUTGOING_INVOICE: "get-outgoing-invoice",
  GET_PUBLIC_OUTGOING_INVOICE: "get-public-outgoing-invoice",
  GET_PUBLIC_PAY_IN_DETAIL_FOR_OUTGOING_INVOICE: "get-public-pay-in-detail-for-outgoing-invoice",
  GET_CASH_FLOW: "get-cash-flow",
  GET_INVOICE_SUMMARY: "get-invoice-summary",
  GET_INVOICE_TIMELINE: "get-invoice-timeline",
  CREATE_INCOMING_INVOICE: "create-incoming-invoice",
  CREATE_OUTGOING_INVOICE: "create-outgoing-invoice",
  CREATE_OUTGOING_INVOICE_PAY_IN: "create-outgoing-invoice-pay-in",
  CREATE_POS_SALE: "create-pos-sale",
  SEND_INVOICE: "send-invoice",
} as const;
